# Generated by Django 3.1.4 on 2021-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210201_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ کامنت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ ثبت نام کاربر'),
        ),
        migrations.AddField(
            model_name='like',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ لایک'),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ پست'),
        ),
    ]
