# Generated by Django 3.1.4 on 2021-02-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_dislikes',
            field=models.IntegerField(default=0, verbose_name='تعداد دیسلایک ها'),
        ),
        migrations.AddField(
            model_name='post',
            name='count_likes',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک ها'),
        ),
    ]
