# Generated by Django 3.1.4 on 2021-02-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210202_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='count_likes',
        ),
    ]
