# Generated by Django 3.1.4 on 2021-02-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('change_comment_show', 'تایید کامنت برای نمایش')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('change_post_show', 'تایید پست برای نمایش'), ('change_post_active', 'فعال بودن پست')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
