# Generated by Django 3.1.4 on 2021-02-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210203_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userImages/%Y/%m/%d/', verbose_name='انتهاب عکس'),
        ),
    ]
